% Report active MATLAB/EEGLAB capabilities without opening EEG data.
% Availability is descriptive only; use references/pipeline.md.

probeNames = [ ...
    "eeglab", "eeg_getversion", "eeg_checkset", "eegh", ...
    "eeg_emptyset", "pop_loadset", "pop_saveset", "std_editset", ...
    "plugin_status", "plugin_getweb", "plugin_askinstall", "plugin_install", ...
    "bids_matlab_tools_ver", ...
    "pop_importbids", "pop_exportbids", ...
    "pop_loadbv", "pop_biosig", "sopen", "pop_fileio", ...
    "pop_ctf_read", "pop_MEF3", ...
    "pop_eegfiltnew", "pop_reref", "pop_interp", ...
    "pop_runica", "pop_iclabel", "pop_clean_rawdata", ...
    "pop_dipfit_settings", "GEDAI", "pop_GEDAI", "eegplugin_GEDAI" ...
];
pluginNames = [ ...
    "EEG-BIDS", "ICLabel", "clean_rawdata", "dipfit", "firfilt", ...
    "bva-io", "Biosig", "File-IO", "MEF3", "GEDAI" ...
];
pluginFields = [ ...
    "eeg_bids", "iclabel", "clean_rawdata", "dipfit", "firfilt", ...
    "bva_io", "biosig", "file_io", "mef3", "gedai" ...
];

probeReport = struct;
probeReport.schema_version = "1.1.0";
probeReport.probe_scope = "active MATLAB session only";
probeReport.matlab_version = string(version);
probeReport.eeglab_version = missing;
probeReport.entry_points = struct;
probeReport.plugins = struct;

for probeIndex = 1:numel(probeNames)
    probeName = probeNames(probeIndex);
    probePath = string(which(probeName));
    probeReport.entry_points.(probeName) = struct( ...
        "available", strlength(probePath) > 0, ...
        "path", probePath ...
    );
end

if probeReport.entry_points.eeg_getversion.available
    try
        probeReport.eeglab_version = string(eeg_getversion);
    catch probeError
        probeReport.eeglab_version = "ERROR: " + string(probeError.message);
    end
end

if probeReport.entry_points.plugin_status.available
    for pluginIndex = 1:numel(pluginNames)
        pluginReport = struct( ...
            "available", false, ...
            "version", missing, ...
            "folder_name", missing, ...
            "function_name", missing, ...
            "error", missing ...
        );
        try
            [pluginStatus, ~, pluginDetails] = plugin_status( ...
                pluginNames(pluginIndex), "exactmatch", 1);
            pluginReport.available = any(pluginStatus == 1);
            if isstruct(pluginDetails) && ~isempty(pluginDetails)
                pluginReport.version = string(pluginDetails(1).version);
                pluginReport.folder_name = string(pluginDetails(1).foldername);
                pluginReport.function_name = string(pluginDetails(1).funcname);
            end
        catch pluginError
            pluginReport.error = string(pluginError.message);
        end
        probeReport.plugins.(pluginFields(pluginIndex)) = pluginReport;
    end
end

probeReport.interpretation = ...
    "Availability only. Verify installed help/signatures, plugin versions, " + ...
    "distribution asset or commit, license, source/write scope, and a " + ...
    "disposable operation smoke test before selection.";

fprintf("%s\n", jsonencode(probeReport));

clear pluginDetails pluginError pluginFields pluginIndex pluginNames ...
    pluginReport pluginStatus probeError probeIndex probeName probeNames ...
    probePath probeReport
