% Report active MATLAB/EEGLAB capabilities without opening EEG data.
% Availability is descriptive only; use references/toolchain-selection.md.

probeNames = [ ...
    "eeglab", "eeg_getversion", "eeg_checkset", "eegh", ...
    "eeg_emptyset", "pop_loadset", "pop_saveset", ...
    "plugin_status", "bids_matlab_tools_ver", ...
    "pop_importbids", "pop_exportbids", ...
    "pop_eegfiltnew", "pop_reref", "pop_interp", ...
    "pop_runica", "pop_iclabel", "pop_clean_rawdata", ...
    "pop_dipfit_settings" ...
];
pluginNames = ["EEG-BIDS", "ICLabel", "clean_rawdata", "dipfit", "firfilt"];
pluginFields = ["eeg_bids", "iclabel", "clean_rawdata", "dipfit", "firfilt"];

probeReport = struct;
probeReport.schema_version = "1.0.0";
probeReport.probe_scope = "active MATLAB session only";
probeReport.matlab_version = string(version);
probeReport.eeglab_version = missing;
probeReport.entry_points = struct;
probeReport.plugins = struct;

for probeIndex = 1:numel(probeNames)
    probeName = probeNames(probeIndex);
    probePath = string(which(probeName));
    probeReport.entry_points.(probeName) = struct( ...
        "available", strlength(probePath) > 0, ...
        "path", probePath ...
    );
end

if probeReport.entry_points.eeg_getversion.available
    try
        probeReport.eeglab_version = string(eeg_getversion);
    catch probeError
        probeReport.eeglab_version = "ERROR: " + string(probeError.message);
    end
end

if probeReport.entry_points.plugin_status.available
    for pluginIndex = 1:numel(pluginNames)
        [pluginStatus, ~, pluginDetails] = plugin_status( ...
            pluginNames(pluginIndex), "exactmatch", 1);
        pluginReport = struct( ...
            "available", any(pluginStatus == 1), ...
            "version", missing, ...
            "folder_name", missing, ...
            "function_name", missing ...
        );
        if isstruct(pluginDetails) && ~isempty(pluginDetails)
            pluginReport.version = string(pluginDetails(1).version);
            pluginReport.folder_name = string(pluginDetails(1).foldername);
            pluginReport.function_name = string(pluginDetails(1).funcname);
        end
        probeReport.plugins.(pluginFields(pluginIndex)) = pluginReport;
    end
end

probeReport.interpretation = [ ...
    "Availability only. Verify installed help/signatures, plugin versions, " ...
    "source/write scope, and a disposable smoke test before selection." ...
];

fprintf("%s\n", jsonencode(probeReport));

clear pluginDetails pluginFields pluginIndex pluginNames pluginReport ...
    pluginStatus probeError probeIndex probeName probeNames probePath probeReport
