function result = verifyEeglabBids( ...
    eeglabRoot, bidsRoot, subjectLabel, taskLabel, runLabel, options)
%VERIFYEEGLABBIDS Exercise one explicit EEG-BIDS selection outside its source.

arguments
    eeglabRoot (1, 1) string {mustBeFolder}
    bidsRoot (1, 1) string {mustBeFolder}
    subjectLabel (1, 1) string
    taskLabel (1, 1) string
    runLabel (1, 1) string
    options.SessionLabel (1, 1) string = ""
end

originalPath = path;
pathCleanup = onCleanup(@() path(originalPath));
addpath(char(eeglabRoot));
[~, ~, ~, ~] = eeglab('nogui');

sourceRoot = resolveFolder(bidsRoot);

outputRoot = string(tempname);
mkdir(outputRoot);
outputCleanup = onCleanup(@() cleanupFolder(outputRoot));
outputRoot = resolveFolder(outputRoot);
assert(~startsWith(lower(outputRoot), lower(sourceRoot + filesep)), ...
    'Temporary derivative output overlaps the BIDS source.');

sourceBefore = snapshotTree(sourceRoot);
selectorArguments = { ...
    'subjects', {char(subjectLabel)}, ...
    'runs', {char(runLabel)}, ...
    'bidstask', char(taskLabel), ...
    'bidsevent', 'on', ...
    'bidschanloc', 'on' ...
};
if strlength(options.SessionLabel) > 0
    selectorArguments = [selectorArguments, ...
        {'sessions', {char(options.SessionLabel)}}];
end

lastwarn('');
[~, ~, noWriteBids, noWriteStats] = pop_importbids( ...
    char(sourceRoot), selectorArguments{:}, ...
    'metadata', 'on', 'outputdir', char(outputRoot));
[noWriteWarning, noWriteWarningId] = lastwarn;

lastwarn('');
[study, recordings, fullBids, fullStats] = pop_importbids( ...
    char(sourceRoot), selectorArguments{:}, ...
    'metadata', 'off', 'outputdir', char(outputRoot), ...
    'studyName', 'eeg-provenance-smoke');
[fullWarning, fullWarningId] = lastwarn;

assert(isscalar(recordings), ...
    'The selectors must resolve exactly one EEG recording.');
sourceAfter = snapshotTree(sourceRoot);
sourceUnchanged = isequal(sourceBefore, sourceAfter);
assert(sourceUnchanged, 'EEG-BIDS changed the source file inventory.');

eventTypes = string({recordings(1).event.type});
[uniqueEventTypes, ~, eventGroups] = unique(eventTypes);
eventCounts = accumarray(eventGroups(:), 1);
outputEntries = dir(fullfile(outputRoot, "**", "*"));
outputEntries = outputEntries(~[outputEntries.isdir]);
outputFiles = string(fullfile({outputEntries.folder}, {outputEntries.name}));
outputFiles = erase(outputFiles, outputRoot + filesep);

result = struct;
result.matlab_version = string(version);
result.eeglab_version = string(eeg_getversion);
result.eegbids_version = string(bids_matlab_tools_ver);
result.selector = struct( ...
    "subject", subjectLabel, ...
    "session", options.SessionLabel, ...
    "task", taskLabel, ...
    "run", runLabel ...
);
result.no_write_pass = struct( ...
    "bids_nonempty", ~isempty(noWriteBids), ...
    "stats_nonempty", ~isempty(noWriteStats), ...
    "warning", string(noWriteWarning), ...
    "warning_id", string(noWriteWarningId) ...
);
result.full_import = struct( ...
    "nbchan", recordings(1).nbchan, ...
    "srate", recordings(1).srate, ...
    "pnts", recordings(1).pnts, ...
    "trials", recordings(1).trials, ...
    "event_count", numel(recordings(1).event), ...
    "event_types", uniqueEventTypes, ...
    "event_counts", eventCounts, ...
    "chanloc_count", numel(recordings(1).chanlocs), ...
    "study_filename", string(study.filename), ...
    "bids_nonempty", ~isempty(fullBids), ...
    "stats_nonempty", ~isempty(fullStats), ...
    "warning", string(fullWarning), ...
    "warning_id", string(fullWarningId) ...
);
result.derivative_files = sort(outputFiles);
result.source_file_count = height(sourceBefore);
result.source_unchanged = sourceUnchanged;
disp(jsonencode(result, PrettyPrint=true));

clear outputCleanup pathCleanup
end

function snapshot = snapshotTree(rootFolder)
entries = dir(fullfile(rootFolder, "**", "*"));
entries = entries(~[entries.isdir]);
paths = string(fullfile({entries.folder}, {entries.name}));
[paths, order] = sort(paths);
snapshot = table( ...
    paths(:), ...
    [entries(order).bytes].', ...
    [entries(order).datenum].', ...
    VariableNames=["Path", "Bytes", "ModifiedDateNumber"] ...
);
end

function cleanupFolder(folder)
if isfolder(folder)
    rmdir(folder, 's');
end
end

function resolvedFolder = resolveFolder(folder)
originalFolder = pwd;
folderCleanup = onCleanup(@() cd(originalFolder));
cd(folder);
resolvedFolder = string(pwd);
clear folderCleanup
end
